# Cache downloaded dependencies and plugins between builds.
# Not strictly necessary, but speeds up the builds.
cache:
  key: "$CI_SSH_KEY"
    # Must be within the repository under test hence we can't use the
    # default ~/.m2
    
variables:
  # Use the cached directory above.
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

deploy:
  image: maven:3.6.1-jdk-11 # docker image with Maven
  before_script:
    # The runners on the forge need a proxy to access the web. mvn
    # ignores the $http_proxy & friends variable => write a
    # configuration file that does this for us.
    - . flyergenerator/setup-mvn-proxy.sh
    - chmod 400 $CI_SSH_KEY
  script:
    - cd /home/gitlabci/mif10-2020/flyergenerator
    - mvn clean package
    - scp -o StrictHostKeyChecking=no -i $CI_SSH_KEY /builds/home/gitlabci/mif10-2020/flyergenerator/target/flyergenerator.war gitlab@192.168.74.210:/opt/tomcat/webapps/v1.war
