# Cache downloaded dependencies and plugins between builds.
# Not strictly necessary, but speeds up the builds.
cache:
  key: "$CI_SSH_KEY"
variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/"

deploy:
  image: maven:3.6.1-jdk-11 # docker image with Maven
  before_script:
    - . flyergenerator/setup-mvn-proxy.sh && chmod 400 $CI_SSH_KEY
  script:
    - cd flyergenerator
    - mvn clean package
    - scp -v -o StrictHostKeyChecking=no -i $CI_SSH_KEY /builds/p1509933/mif10-2020/flyergenerator/target/flyergenerator.war gitlabci@192.168.74.210:/opt/tomcat/webapps/flyergenerator.war
