CREATE TABLE UTILISATEUR
(
  ID_UTILISATEUR INTEGER PRIMARY KEY,
  PSEUDO VARCHAR(255) NOT NULL,
  MOT_DE_PASSE VARCHAR(255) NOT NULL
);

DROP TABLE EVENT CASCADE;
CREATE TABLE EVENT
(
  ID_EVENT INTEGER,
  ID_UTILISATEUR INTEGER REFERENCES UTILISATEUR (ID_UTILISATEUR),
  NOM VARCHAR(255) NOT NULL,
  LIEU VARCHAR(255) NOT NULL,
  VILLE VARCHAR(255) NOT NULL,
  PRIX INTEGER,
  PATH_IMG_BACK VARCHAR(255),
  HEUREDEB TIME, 
  DATEDEB DATE NOT NULL,
  ID_CONTACT INTEGER,
  FOREIGN KEY (ID_CONTACT) REFERENCES CONTACT(ID_CONTACT),
  PRIMARY KEY (ID_EVENT)
);

DROP TABLE COMPETITION;
CREATE TABLE COMPETITION
(
  ID_EVENT INTEGER,
  ID_UTILISATEUR INTEGER REFERENCES UTILISATEUR (ID_UTILISATEUR),
  NOM VARCHAR(255) NOT NULL,
  LIEU VARCHAR(255) NOT NULL,
  VILLE VARCHAR(255) NOT NULL,
  PRIX INTEGER,
  PATH_IMG_BACK VARCHAR(255),
  HEUREDEB TIME NOT NULL, 
  DATEDEB DATE NOT NULL,
  ID_CONTACT INTEGER,
  HASHTAG VARCHAR(255),
  RESUME VARCHAR(255),
  CASHPRIZE VARCHAR(255),
  FOREIGN KEY (ID_CONTACT) REFERENCES CONTACT(ID_CONTACT),
  PRIMARY KEY (ID_EVENT)
);

DROP TABLE CONTACT CASCADE;
CREATE TABLE CONTACT
(
  ID_CONTACT INTEGER,
  ID_EVENT INTEGER,
  NOM VARCHAR(255) NOT NULL,
  NUMERO INTEGER NOT NULL,
  MAIL VARCHAR(255) NOT NULL,
  PRIMARY KEY (ID_CONTACT),
  FOREIGN KEY (ID_EVENT) REFERENCES EVENT(ID_EVENT)
);

DROP TABLE SPECTACLE;
CREATE TABLE SPECTACLE
(
  ID_EVENT INTEGER,
  ID_UTILISATEUR INTEGER REFERENCES UTILISATEUR (ID_UTILISATEUR),
  NOM VARCHAR(255) NOT NULL,
  LIEU VARCHAR(255) NOT NULL,
  VILLE VARCHAR(255) NOT NULL,
  PRIX INTEGER NOT NULL,
  PATH_IMG_BACK VARCHAR(255),
  HEUREDEB TIME NOT NULL, 
  ARTISTES VARCHAR(255) NOT NULL,
  DATEDEB DATE NOT NULL,
  NOM_ASSO VARCHAR(255) NOT NULL,
  ID_CONTACT INTEGER,
  FOREIGN KEY (ID_CONTACT) REFERENCES CONTACT(ID_CONTACT),
  PRIMARY KEY (ID_EVENT)
);


DROP TABLE CONFERENCE;
CREATE TABLE CONFERENCE
(
  ID_EVENT INTEGER,
  RESUMEE VARCHAR(255) NOT NULL,
  ID_UTILISATEUR INTEGER REFERENCES UTILISATEUR (ID_UTILISATEUR),
  NOM VARCHAR(255) NOT NULL,
  LIEU VARCHAR(255) NOT NULL,
  VILLE VARCHAR(255) NOT NULL,
  PRIX INTEGER,
  PATH_IMG_BACK VARCHAR(255),
  HEUREDEB TIME NOT NULL, 
  INTERVENANTS VARCHAR(255) NOT NULL,
  DATEDEB DATE NOT NULL,
  ID_CONTACT INTEGER NOT NULL,
  FOREIGN KEY (ID_CONTACT) REFERENCES CONTACT(ID_CONTACT),
  PRIMARY KEY (ID_EVENT)
);

DROP TABLE EXPOSITION;
CREATE TABLE EXPOSITION
(
  ID_EVENT INTEGER,
  ID_UTILISATEUR INTEGER REFERENCES UTILISATEUR (ID_UTILISATEUR),
  NOM VARCHAR(255) NOT NULL,
  LIEU VARCHAR(255) NOT NULL,
  VILLE VARCHAR(255) NOT NULL,
  PRIX INTEGER,
  PATH_IMG_BACK VARCHAR(255),
  HEUREDEB TIME NOT NULL, 
  HEUREDEF TIME NOT NULL,
  DATEDEB DATE NOT NULL,
  DATEDEF DATE NOT NULL,
  THEME VARCHAR(255) NOT NULL,
  ID_CONTACT INTEGER,
  FOREIGN KEY (ID_CONTACT) REFERENCES CONTACT(ID_CONTACT),
  PRIMARY KEY ( ID_EVENT)
);
